import Navbar from "@/components/Navbar";
import Provider from "@components/Provider";
import "@styles/global.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="app">
        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
